name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  NAME: pihome-gateway-hack
  TAG: latest
  
jobs:

  build:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ env.NAME }}:$(date +%s)
     
    - name: Login to GHCR
      run: docker login ghcr.io --username ${{ github.actor }} --password $GHCR_PAT
     
    - name: Tag
      run: docker tag app ghcr.io/${{ github.actor }}/$NAME:$TAG
     
    - name: Push
      run: docker push ghcr.io/${{ github.actor }}/$NAME:$TAG
      
